import express from "express";
import sequelize from "./src/database/models/db";
import userRoutes from "./src/routes/userRoutes";
import farmerRoutes from "./src/routes/farmerRoutes";
import coldStorageRoutes from "./src/routes/coldStorageRoutes";
import agentRoutes from "./src/routes/agentRoutes";
import locationRoutes from "./src/routes/locationRoutes";
import adminIrrigationRoutes from "./src/routes/adminRoutes/farmer/adminIrrigationRoutes";
import adminSoilTypeRoutes from "./src/routes/adminRoutes/farmer/adminSoilTypeRoutes";
import adminPotatoVarietyRoutes from "./src/routes/adminRoutes/farmer/adminPotatoVarietyRoutes";
import adminPotatoSubVarietyRoutes from "./src/routes/adminRoutes/farmer/adminPotatoSubVarietyRoutes";
import adminSowingMethodRoutes from "./src/routes/adminRoutes/farmer/adminSowingMethodRoutes";
import adminFarmEquipmentRoutes from "./src/routes/adminRoutes/farmer/adminFarmEquipmentUsedRoutes";
import adminTechnologyUsedRoutes from "./src/routes/adminRoutes/farmer/adminTechnologyUsedRoutes";
import adminPriceDiscoveryRoutes from "./src/routes/adminRoutes/farmer/adminPriceDiscoveryRoutes";
import adminBrandPreferenceReasonRoutes from "./src/routes/adminRoutes/farmer/adminBrandPreferenceReasonRoutes";
import adminSeedBrandRoutes from "./src/routes/adminRoutes/farmer/adminSeedBrandRoutes";
import adminSellingChannelRoutes from "./src/routes/adminRoutes/farmer/adminSellingChannelRoutes";
import adminSellingPlaceRoutes from "./src/routes/adminRoutes/farmer/adminSellingPlaceRoutes";
import adminSellingPriceRoutes from "./src/routes/adminRoutes/farmer/adminSellingPriceRoutes";
import adminBiggestChallengeInSellingRoutes from "./src/routes/adminRoutes/farmer/adminBiggestChallengeInSellingRoutes";
import adminCropTradedRoutes from "./src/routes/adminRoutes/trader/adminCropTradedRoutes";
import adminTraderInterestRoutes from "./src/routes/adminRoutes/trader/adminTraderInterestRoutes";
import adminTraderTypeRoutes from "./src/routes/adminRoutes/trader/adminTraderTypeRoutes";
import adminTraderVarietyRoutes from "./src/routes/adminRoutes/trader/adminTraderVarietyRoutes";
import adminMarketCoverageRoutes from "./src/routes/adminRoutes/trader/adminMarketCoverageRoutes";
import adminStorageTypeRoutes from "./src/routes/adminRoutes/coldStorage/adminStorageTypeRoutes";
import adminUsageTypeRoutes from "./src/routes/adminRoutes/coldStorage/adminUsageTypeRoutes";
import adminOperationalChallengeRoutes from "./src/routes/adminRoutes/coldStorage/adminOperationalChallengeRoutes";
import adminIrrigationMethodRoutes from "./src/routes/adminRoutes/farmer/adminIrrigationMethodRoutes";
import adminConstructionTypeRoutes from "./src/routes/adminRoutes/coldStorage/adminConstructionTypeRoutes";
import adminColdStorageTypeRoutes from "./src/routes/adminRoutes/coldStorage/adminColdStorageTypeRoutes";
import adminRoofTypeRoutes from "./src/routes/adminRoutes/coldStorage/adminRoofTypeRoutes";
import adminStorageFeatureRoutes from "./src/routes/adminRoutes/coldStorage/adminStorageFeatureRoutes";
import adminDryingFacilityDetailRoutes from "./src/routes/adminRoutes/coldStorage/adminDryingFacilityDetailRoutes";
import adminElevatoTypeRoutes from "./src/routes/adminRoutes/coldStorage/adminElevatorTypeRoutes";
import adminMonitoringFacilityRoutes from "./src/routes/adminRoutes/coldStorage/adminMonitoringFacilityRoutes";
import adminPowerFacilityRoutes from "./src/routes/adminRoutes/coldStorage/adminPowerFacilityRoutes";
import adminPotatoDisposalSystemRoutes from "./src/routes/adminRoutes/coldStorage/adminPotatoDisposalSystemRoutes";
import adminOtherFacilityRoutes from "./src/routes/adminRoutes/coldStorage/adminOtherFacilityRoutes";
import adminStorageBookingSystemRoutes from "./src/routes/adminRoutes/coldStorage/adminStorageBookingSystemRoutes";
import traderRoutes from "./src/routes/traderRoutes";
import uploadRoutes from "./src/routes/uploadRoutes";
import csRequirementRoutes from "./src/routes/csRequirementRoutes";
import subAdminRoutes from "./src/routes/subAdminRoutes";
import mandiAgentRoutes from "./src/routes/mandiAgentRoutes";
import govSchemeRoutes from "./src/routes/govSchemeRoutes";
import newsRoutes from "./src/routes/newsRoutes";
import kycRoutes from "./src/routes/kycRoutes";
import eventRoutes from "./src/routes/eventRoutes";
import buyRequestRoutes from "./src/routes/buyRequestRoutes";
import sellRequestRoutes from "./src/routes/sellRequestRoutes";
import favRequestRoutes from "./src/routes/favRequestRoutes";
import mandiPriceRoutes from "./src/routes/mandiPriceRoutes";
import subAdminWebRoutes from "./src/routes/subAdminWebRoutes";
import mandiListRoutes from "./src/routes/mandiListRoutes";
import adminDryingMethodRoutes from "./src/routes/adminRoutes/coldStorage/adminDryingMethodRoutes";
import bannerRoutes from "./src/routes/bannerRoutes";
import advertisementServiceRoutes from "./src/routes/adminRoutes/mobile/advertisementServiceRoutes";
import adverisementRoutes from "./src/routes/advertisementRoutes";
import contentManagementRoutes from "./src/routes/contentManagementRoutes";
import faqCategoryRoutes from "./src/routes/adminRoutes/mobile/faqCategoryRoutes";
import faqRoutes from "./src/routes/faqRoutes";
import contactSupportRoutes from "./src/routes/contactSupportRoutes";
import cropDiagnosisRoutes from "./src/routes/cropDiagnosisRoutes";
import promotionRequestRoutes from "./src/routes/promotionRequestRoutes";
import userRegistrationRoutes from "./src/routes/userRegistrationRoutes";
import askExpertRoutes from "./src/routes/askExpertRoutes";
import directoryRoutes from "./src/routes/directoryRoutes";
import directoryCategoryRoutes from "./src/routes/adminRoutes/directory/directoryCategoryRoutes";
import directorySubCategoryRoutes from "./src/routes/adminRoutes/directory/directorySubCategoryRoutes";
import notificationRoutes from "./src/routes/notificationRoutes";
import knowledgeHubRoutes from "./src/routes/knowledgeHubRoutes";
import openMarketPlaceRoutes from "./src/routes/openMarketPlaceRoutes";
import jobRoutes from "./src/routes/jobRoutes";
import communityRoutes from "./src/routes/communityRoutes";
import transportServiceRoutes from "./src/routes/transportServiceRoutes";
import transportRequirementRoutes from "./src/routes/transportRequirementRoutes";
import walletRoutes from "./src/routes/walletRoutes";
import directorySubscriptionRoutes from "./src/routes/directorySubscriptionRoutes";
import bannerAdRoutes from "./src/routes/bannerAdRoutes";
import contactUnlockRoutes from "./src/routes/contactUnlockRoutes";
import userSubscriptionRoutes from "./src/routes/userSubscriptionRoutes";

const cors = require("cors");

const app = express();
app.use(cors());

app.use(express.json());

app.use("/api/users", userRoutes);
app.use("/api/farmers", farmerRoutes);
app.use("/api/cold-storage", coldStorageRoutes);
app.use("/api/agent", agentRoutes);
app.use("/api/locations", locationRoutes);
app.use("/api/admin/irrigation_source", adminIrrigationRoutes);
app.use("/api/admin/soil_type", adminSoilTypeRoutes);
app.use("/api/admin/potato_variety", adminPotatoVarietyRoutes);
app.use("/api/admin/potato_sub_variety", adminPotatoSubVarietyRoutes);
app.use("/api/admin/sowing_method", adminSowingMethodRoutes);
app.use("/api/admin/farm_equipment", adminFarmEquipmentRoutes);
app.use("/api/admin/technology_used", adminTechnologyUsedRoutes);
app.use("/api/admin/price_discovery", adminPriceDiscoveryRoutes);
app.use("/api/admin/crop_traded", adminCropTradedRoutes);
app.use("/api/admin/trader_interest", adminTraderInterestRoutes);
app.use("/api/admin/trader_type", adminTraderTypeRoutes);
app.use("/api/admin/trader_variety", adminTraderVarietyRoutes);
app.use("/api/admin/market_coverage", adminMarketCoverageRoutes);
app.use(
  "/api/admin/challenge_in_selling",
  adminBiggestChallengeInSellingRoutes,
);
app.use("/api/admin/storage_type", adminStorageTypeRoutes);
app.use("/api/admin/usage_type", adminUsageTypeRoutes);
app.use("/api/admin/construction_type", adminConstructionTypeRoutes);
app.use("/api/admin/coldStorage_type", adminColdStorageTypeRoutes);
app.use("/api/admin/roof_type", adminRoofTypeRoutes);
app.use("/api/admin/storage_feature", adminStorageFeatureRoutes);
app.use("/api/admin/drying_facility", adminDryingFacilityDetailRoutes);
app.use("/api/admin/elevator_type", adminElevatoTypeRoutes);
app.use("/api/admin/monitoring_facility", adminMonitoringFacilityRoutes);
app.use("/api/admin/power_facility", adminPowerFacilityRoutes);
app.use("/api/admin/potato_disposal_system", adminPotatoDisposalSystemRoutes);
app.use("/api/admin/other_facility", adminOtherFacilityRoutes);
app.use("/api/admin/storage_booking_system", adminStorageBookingSystemRoutes);
app.use("/api/admin/brand_preference_reason", adminBrandPreferenceReasonRoutes);
app.use("/api/admin/seed_brand", adminSeedBrandRoutes);
app.use("/api/admin/selling_channel", adminSellingChannelRoutes);
app.use("/api/admin/selling_place", adminSellingPlaceRoutes);
app.use("/api/admin/selling_price", adminSellingPriceRoutes);
app.use("/api/admin/irrigation_method", adminIrrigationMethodRoutes);
app.use("/api/admin/operational_challenge", adminOperationalChallengeRoutes);
app.use("/api/traders", traderRoutes);
app.use("/api", uploadRoutes);
app.use("/api/requirements", csRequirementRoutes);
app.use("/api/sub_admins", subAdminRoutes);
app.use("/api/mandi_agent", mandiAgentRoutes);
app.use("/api/government_schemes", govSchemeRoutes);
app.use("/api/news", newsRoutes);
app.use("/api/kyc", kycRoutes);
app.use("/api/events", eventRoutes);
app.use("/api/buy_requests", buyRequestRoutes);
app.use("/api/sell_requests", sellRequestRoutes);
app.use("/api/favourite", favRequestRoutes);
app.use("/api/mandi_prices", mandiPriceRoutes);
app.use("/api/web_sub_admins", subAdminWebRoutes);
app.use("/api/mandi", mandiListRoutes);
app.use("/api/admin/drying_methods", adminDryingMethodRoutes);
app.use("/api/banner", bannerRoutes);
app.use("/api/admin/advertisement_services", advertisementServiceRoutes);
app.use("/api/advertisement", adverisementRoutes);
app.use("/api/content_management", contentManagementRoutes);
app.use("/api/admin/faq_categories", faqCategoryRoutes);
app.use("/api/faqs", faqRoutes);
app.use("/api/contact_support", contactSupportRoutes);
app.use("/api/crop_diagnosis", cropDiagnosisRoutes);
app.use("/api/promotion_requests", promotionRequestRoutes);
app.use("/api/user_registrations", userRegistrationRoutes);
app.use("/api/ask_experts", askExpertRoutes);
app.use("/api/admin/potato_variety", adminPotatoVarietyRoutes);
app.use("/api/directory_categories", directoryCategoryRoutes);
app.use("/api/directory_sub_categories", directorySubCategoryRoutes);
app.use("/api/directories", directoryRoutes);
app.use("/api/notifications", notificationRoutes);
app.use("/api/knowledge_hubs", knowledgeHubRoutes);
app.use("/api/open_market_places", openMarketPlaceRoutes);
app.use("/api/jobs", jobRoutes);
app.use("/api/community_posts", communityRoutes);
app.use("/api/transport_services", transportServiceRoutes);
app.use("/api/transport_requirements", transportRequirementRoutes);
app.use("/api/wallets", walletRoutes);
app.use("/api/directory_subscription", directorySubscriptionRoutes);
app.use("/api/banner_ad", bannerAdRoutes);
app.use("/api", contactUnlockRoutes);
app.use("/api/user_subscription", userSubscriptionRoutes);

const PORT = 8000;
const startServer = async () => {
  try {
    await sequelize.authenticate();
    console.log("Database connected!");
    app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
  } catch (error) {
    console.error("Database connection failed:", error);
  }
};

startServer();
